package icu.takeneko.towel.coremod;

import java.util.List;
import java.util.Map;
import java.util.Set;

import com.gtnewhorizon.gtnhmixins.IEarlyMixinLoader;

import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.relauncher.IFMLLoadingPlugin;
import icu.takeneko.towel.Tags;
import icu.takeneko.towel.helpers.mixin.MixinUtils;

@IFMLLoadingPlugin.MCVersion("1.7.10")
public class TCoreMod extends DummyModContainer implements IFMLLoadingPlugin, IEarlyMixinLoader {

    public static final String[] DEFAULT_TRANSFORMERS = new String[] {
        "icu.takeneko.tick.coremod.TDelegatedTransformer" };

    public TCoreMod() {
        super(new ModMetadata());
        ModMetadata md = getMetadata();
        md.autogenerated = true;
        md.modId = md.name = "Tick CoreMod";
        md.parent = "command-tick";
        md.version = Tags.VERSION;
    }

    @Override
    public String[] getASMTransformerClass() {
        return DEFAULT_TRANSFORMERS;
    }

    @Override
    public String getModContainerClass() {
        return "icu.takeneko.tick.coremod.TCoreMod";
    }

    @Override
    public String getSetupClass() {
        return null;
    }

    @Override
    public void injectData(Map<String, Object> data) {

    }

    @Override
    public String getAccessTransformerClass() {
        return null;
    }

    @Override
    public String getMixinConfig() {
        return "mixins.towel.early.json";
    }

    @Override
    public List<String> getMixins(Set<String> loadedCoreMods) {
        return MixinUtils.getEarlyMixins(loadedCoreMods);
    }
}
